<?php

namespace Database\Seeders;

use App\Modules\Payments\Models\PaymentGateway;
use Illuminate\Database\Seeder;

class PaymentGatewaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $gateways = [
            [
                'name' => 'Stripe',
                'slug' => 'stripe',
                'type' => 'fiat',
                'description' => 'Accept credit cards, debit cards, and digital wallets from customers worldwide.',
                'logo' => 'stripe-logo.png',
                'supported_currencies' => ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'INR', 'SGD', 'HKD'],
                'supported_countries' => ['US', 'GB', 'CA', 'AU', 'IN', 'SG', 'HK'],
                'transaction_fee_percentage' => 2.9,
                'transaction_fee_fixed' => 0.30,
                'transaction_fee_currency' => 'USD',
                'min_amount' => 0.50,
                'max_amount' => 999999.99,
                'processing_time_minutes' => 1,
                'webhook_url' => '/webhooks/stripe',
                'test_mode' => true,
                'sort_order' => 1,
                'user_instructions' => 'Pay securely with your credit or debit card through Stripe.',
                'admin_notes' => 'Requires Stripe account and API keys. Install: composer require stripe/stripe-php',
                'is_active' => false,
                'config' => [
                    'live_public_key' => '',
                    'live_secret_key' => '',
                ],
                'sandbox_config' => [
                    'test_public_key' => '',
                    'test_secret_key' => '',
                ],
            ],
            [
                'name' => 'PayPal',
                'slug' => 'paypal',
                'type' => 'fiat',
                'description' => 'Accept PayPal, credit cards, and debit cards from customers worldwide.',
                'logo' => 'paypal-logo.png',
                'supported_currencies' => ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY'],
                'supported_countries' => ['US', 'GB', 'CA', 'AU', 'DE', 'FR', 'IT', 'ES'],
                'transaction_fee_percentage' => 2.9,
                'transaction_fee_fixed' => 0.30,
                'transaction_fee_currency' => 'USD',
                'min_amount' => 1.00,
                'max_amount' => 10000.00,
                'processing_time_minutes' => 1,
                'test_mode' => true,
                'sort_order' => 2,
                'user_instructions' => 'Pay with your PayPal account or credit/debit card.',
                'admin_notes' => 'Requires PayPal Business account and API credentials.',
                'is_active' => false,
                'config' => [
                    'client_id' => '',
                    'secret' => '',
                    'mode' => 'live',
                ],
                'sandbox_config' => [
                    'client_id' => '',
                    'secret' => '',
                    'mode' => 'sandbox',
                ],
            ],
            [
                'name' => 'Razorpay',
                'slug' => 'razorpay',
                'type' => 'fiat',
                'description' => 'Accept payments via UPI, cards, net banking, and wallets. Popular in India.',
                'logo' => 'razorpay-logo.png',
                'supported_currencies' => ['INR'],
                'supported_countries' => ['IN'],
                'transaction_fee_percentage' => 2.0,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'INR',
                'min_amount' => 1.00,
                'max_amount' => 1000000.00,
                'processing_time_minutes' => 1,
                'test_mode' => true,
                'sort_order' => 3,
                'user_instructions' => 'Pay using UPI, cards, net banking, or popular wallets.',
                'admin_notes' => 'Best for Indian market. Supports UPI and local payment methods.',
                'is_active' => false,
                'config' => [
                    'key_id' => '',
                    'key_secret' => '',
                ],
                'sandbox_config' => [
                    'key_id' => '',
                    'key_secret' => '',
                ],
            ],
            [
                'name' => 'Bitcoin (BTC)',
                'slug' => 'bitcoin',
                'type' => 'crypto',
                'description' => 'Accept Bitcoin payments with on-chain confirmations.',
                'logo' => 'bitcoin-logo.png',
                'supported_currencies' => ['BTC'],
                'transaction_fee_percentage' => 1.0,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'BTC',
                'min_amount' => 0.0001,
                'max_amount' => 100.00,
                'processing_time_minutes' => 60, // ~10 minutes per confirmation, 6 confirmations typical
                'test_mode' => false,
                'sort_order' => 10,
                'user_instructions' => 'Send Bitcoin to the provided address. Requires 3 confirmations.',
                'admin_notes' => 'Requires Bitcoin node or payment processor integration.',
                'is_active' => false,
                'config' => [
                    'wallet_address' => '',
                    'required_confirmations' => 3,
                ],
            ],
            [
                'name' => 'Ethereum (ETH)',
                'slug' => 'ethereum',
                'type' => 'crypto',
                'description' => 'Accept Ethereum and ERC-20 tokens.',
                'logo' => 'ethereum-logo.png',
                'supported_currencies' => ['ETH', 'USDT', 'USDC'],
                'transaction_fee_percentage' => 1.0,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'ETH',
                'min_amount' => 0.001,
                'max_amount' => 1000.00,
                'processing_time_minutes' => 15,
                'test_mode' => false,
                'sort_order' => 11,
                'user_instructions' => 'Send Ethereum or ERC-20 tokens to the provided address.',
                'admin_notes' => 'Supports ETH and ERC-20 tokens like USDT and USDC.',
                'is_active' => false,
                'config' => [
                    'wallet_address' => '',
                    'required_confirmations' => 12,
                ],
            ],
            [
                'name' => 'Coinbase Commerce',
                'slug' => 'coinbase',
                'type' => 'crypto',
                'description' => 'Accept Bitcoin, Ethereum, Litecoin, and more through Coinbase Commerce.',
                'logo' => 'coinbase-logo.png',
                'supported_currencies' => ['BTC', 'ETH', 'LTC', 'BCH', 'USDC'],
                'transaction_fee_percentage' => 1.0,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'USD',
                'min_amount' => 1.00,
                'max_amount' => 100000.00,
                'processing_time_minutes' => 15,
                'test_mode' => true,
                'sort_order' => 12,
                'user_instructions' => 'Pay with your preferred cryptocurrency through Coinbase.',
                'admin_notes' => 'Requires Coinbase Commerce account and API key.',
                'is_active' => false,
                'config' => [
                    'api_key' => '',
                    'webhook_secret' => '',
                ],
            ],
            [
                'name' => 'Paytm',
                'slug' => 'paytm',
                'type' => 'fiat',
                'description' => 'Popular Indian payment gateway supporting UPI, cards, wallets, and net banking.',
                'logo' => 'paytm-logo.png',
                'supported_currencies' => ['INR'],
                'supported_countries' => ['IN'],
                'transaction_fee_percentage' => 2.0,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'INR',
                'min_amount' => 1.00,
                'max_amount' => 1000000.00,
                'processing_time_minutes' => 1,
                'webhook_url' => '/webhooks/paytm',
                'test_mode' => true,
                'sort_order' => 4,
                'user_instructions' => 'Pay using Paytm wallet, UPI, cards, or net banking.',
                'admin_notes' => 'Requires Paytm merchant account. Popular in India.',
                'is_active' => false,
                'config' => [
                    'merchant_id' => '',
                    'merchant_key' => '',
                    'website' => 'DEFAULT',
                    'industry_type' => 'Retail',
                ],
                'sandbox_config' => [
                    'merchant_id' => '',
                    'merchant_key' => '',
                    'website' => 'WEBSTAGING',
                    'industry_type' => 'Retail',
                ],
            ],
            [
                'name' => 'PhonePe',
                'slug' => 'phonepe',
                'type' => 'fiat',
                'description' => 'Leading UPI payment solution in India with instant settlements.',
                'logo' => 'phonepe-logo.png',
                'supported_currencies' => ['INR'],
                'supported_countries' => ['IN'],
                'transaction_fee_percentage' => 1.99,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'INR',
                'min_amount' => 1.00,
                'max_amount' => 100000.00,
                'processing_time_minutes' => 0,
                'webhook_url' => '/webhooks/phonepe',
                'test_mode' => true,
                'sort_order' => 5,
                'user_instructions' => 'Pay instantly using PhonePe UPI or wallet.',
                'admin_notes' => 'Requires PhonePe merchant account. Instant UPI payments.',
                'is_active' => false,
                'config' => [
                    'merchant_id' => '',
                    'salt_key' => '',
                    'salt_index' => '',
                ],
                'sandbox_config' => [
                    'merchant_id' => '',
                    'salt_key' => '',
                    'salt_index' => '',
                ],
            ],
            [
                'name' => 'Cashfree',
                'slug' => 'cashfree',
                'type' => 'fiat',
                'description' => 'Indian payment gateway with support for UPI, cards, wallets, and net banking.',
                'logo' => 'cashfree-logo.png',
                'supported_currencies' => ['INR'],
                'supported_countries' => ['IN'],
                'transaction_fee_percentage' => 1.95,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'INR',
                'min_amount' => 1.00,
                'max_amount' => 1000000.00,
                'processing_time_minutes' => 1,
                'webhook_url' => '/webhooks/cashfree',
                'test_mode' => true,
                'sort_order' => 6,
                'user_instructions' => 'Pay using UPI, cards, wallets, or net banking through Cashfree.',
                'admin_notes' => 'Lower transaction fees, great for Indian market.',
                'is_active' => false,
                'config' => [
                    'app_id' => '',
                    'secret_key' => '',
                ],
                'sandbox_config' => [
                    'app_id' => '',
                    'secret_key' => '',
                ],
            ],
            [
                'name' => 'Instamojo',
                'slug' => 'instamojo',
                'type' => 'fiat',
                'description' => 'Easy payment gateway for Indian businesses supporting all major payment methods.',
                'logo' => 'instamojo-logo.png',
                'supported_currencies' => ['INR'],
                'supported_countries' => ['IN'],
                'transaction_fee_percentage' => 2.0,
                'transaction_fee_fixed' => 3.00,
                'transaction_fee_currency' => 'INR',
                'min_amount' => 9.00,
                'max_amount' => 200000.00,
                'processing_time_minutes' => 1,
                'webhook_url' => '/webhooks/instamojo',
                'test_mode' => true,
                'sort_order' => 7,
                'user_instructions' => 'Pay with cards, net banking, UPI, or wallets.',
                'admin_notes' => 'Easy setup for small businesses. Popular in India.',
                'is_active' => false,
                'config' => [
                    'api_key' => '',
                    'auth_token' => '',
                    'salt' => '',
                ],
                'sandbox_config' => [
                    'api_key' => '',
                    'auth_token' => '',
                    'salt' => '',
                ],
            ],
            [
                'name' => 'CCAvenue',
                'slug' => 'ccavenue',
                'type' => 'fiat',
                'description' => 'India\'s largest payment gateway with support for 200+ payment options.',
                'logo' => 'ccavenue-logo.png',
                'supported_currencies' => ['INR', 'USD', 'EUR', 'GBP', 'AUD', 'CAD'],
                'supported_countries' => ['IN', 'US', 'GB', 'AU', 'CA'],
                'transaction_fee_percentage' => 2.0,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'INR',
                'min_amount' => 1.00,
                'max_amount' => 1000000.00,
                'processing_time_minutes' => 1,
                'webhook_url' => '/webhooks/ccavenue',
                'test_mode' => true,
                'sort_order' => 8,
                'user_instructions' => 'Choose from over 200 payment options including cards, UPI, and wallets.',
                'admin_notes' => 'Comprehensive payment solution with international support.',
                'is_active' => false,
                'config' => [
                    'merchant_id' => '',
                    'access_code' => '',
                    'working_key' => '',
                ],
                'sandbox_config' => [
                    'merchant_id' => '',
                    'access_code' => '',
                    'working_key' => '',
                ],
            ],
            [
                'name' => 'Square',
                'slug' => 'square',
                'type' => 'fiat',
                'description' => 'Accept credit cards and digital wallets with Square\'s payment processing.',
                'logo' => 'square-logo.png',
                'supported_currencies' => ['USD', 'CAD', 'AUD', 'GBP', 'EUR', 'JPY'],
                'supported_countries' => ['US', 'CA', 'AU', 'GB', 'FR', 'DE', 'JP'],
                'transaction_fee_percentage' => 2.9,
                'transaction_fee_fixed' => 0.30,
                'transaction_fee_currency' => 'USD',
                'min_amount' => 1.00,
                'max_amount' => 999999.99,
                'processing_time_minutes' => 1,
                'webhook_url' => '/webhooks/square',
                'test_mode' => true,
                'sort_order' => 9,
                'user_instructions' => 'Pay securely with credit card or digital wallet through Square.',
                'admin_notes' => 'Popular in US and international markets. Requires Square account.',
                'is_active' => false,
                'config' => [
                    'application_id' => '',
                    'access_token' => '',
                    'location_id' => '',
                ],
                'sandbox_config' => [
                    'application_id' => '',
                    'access_token' => '',
                    'location_id' => '',
                ],
            ],
            [
                'name' => 'Authorize.Net',
                'slug' => 'authorizenet',
                'type' => 'fiat',
                'description' => 'Trusted payment gateway for accepting credit cards and e-checks.',
                'logo' => 'authorizenet-logo.png',
                'supported_currencies' => ['USD', 'CAD', 'GBP', 'EUR', 'AUD'],
                'supported_countries' => ['US', 'CA', 'GB', 'AU'],
                'transaction_fee_percentage' => 2.9,
                'transaction_fee_fixed' => 0.30,
                'transaction_fee_currency' => 'USD',
                'min_amount' => 1.00,
                'max_amount' => 999999.99,
                'processing_time_minutes' => 1,
                'webhook_url' => '/webhooks/authorizenet',
                'test_mode' => true,
                'sort_order' => 10,
                'user_instructions' => 'Pay with credit card or e-check through Authorize.Net.',
                'admin_notes' => 'Established payment processor with reliable service.',
                'is_active' => false,
                'config' => [
                    'api_login_id' => '',
                    'transaction_key' => '',
                    'signature_key' => '',
                ],
                'sandbox_config' => [
                    'api_login_id' => '',
                    'transaction_key' => '',
                    'signature_key' => '',
                ],
            ],
            [
                'name' => 'Mollie',
                'slug' => 'mollie',
                'type' => 'fiat',
                'description' => 'European payment service provider supporting all major payment methods.',
                'logo' => 'mollie-logo.png',
                'supported_currencies' => ['EUR', 'USD', 'GBP', 'CHF', 'DKK', 'SEK', 'NOK', 'PLN'],
                'supported_countries' => ['NL', 'BE', 'DE', 'FR', 'GB', 'AT', 'CH', 'PL'],
                'transaction_fee_percentage' => 2.8,
                'transaction_fee_fixed' => 0.25,
                'transaction_fee_currency' => 'EUR',
                'min_amount' => 0.01,
                'max_amount' => 999999.99,
                'processing_time_minutes' => 1,
                'webhook_url' => '/webhooks/mollie',
                'test_mode' => true,
                'sort_order' => 11,
                'user_instructions' => 'Pay with iDEAL, credit card, SEPA, or other European payment methods.',
                'admin_notes' => 'Best for European market. Supports iDEAL, Bancontact, etc.',
                'is_active' => false,
                'config' => [
                    'api_key' => '',
                ],
                'sandbox_config' => [
                    'api_key' => '',
                ],
            ],
            [
                'name' => 'Braintree',
                'slug' => 'braintree',
                'type' => 'fiat',
                'description' => 'PayPal-owned payment gateway supporting credit cards, PayPal, and digital wallets.',
                'logo' => 'braintree-logo.png',
                'supported_currencies' => ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'SGD', 'HKD', 'MYR'],
                'supported_countries' => ['US', 'CA', 'GB', 'AU', 'SG', 'HK', 'MY'],
                'transaction_fee_percentage' => 2.9,
                'transaction_fee_fixed' => 0.30,
                'transaction_fee_currency' => 'USD',
                'min_amount' => 1.00,
                'max_amount' => 999999.99,
                'processing_time_minutes' => 1,
                'webhook_url' => '/webhooks/braintree',
                'test_mode' => true,
                'sort_order' => 12,
                'user_instructions' => 'Pay with credit card, PayPal, Venmo, or Apple Pay.',
                'admin_notes' => 'Owned by PayPal. Great for international businesses.',
                'is_active' => false,
                'config' => [
                    'merchant_id' => '',
                    'public_key' => '',
                    'private_key' => '',
                ],
                'sandbox_config' => [
                    'merchant_id' => '',
                    'public_key' => '',
                    'private_key' => '',
                ],
            ],
            [
                'name' => 'Paystack',
                'slug' => 'paystack',
                'type' => 'fiat',
                'description' => 'African payment gateway supporting cards, bank transfers, and mobile money.',
                'logo' => 'paystack-logo.png',
                'supported_currencies' => ['NGN', 'GHS', 'ZAR', 'USD'],
                'supported_countries' => ['NG', 'GH', 'ZA'],
                'transaction_fee_percentage' => 1.5,
                'transaction_fee_fixed' => 100.00,
                'transaction_fee_currency' => 'NGN',
                'min_amount' => 100.00,
                'max_amount' => 10000000.00,
                'processing_time_minutes' => 1,
                'webhook_url' => '/webhooks/paystack',
                'test_mode' => true,
                'sort_order' => 13,
                'user_instructions' => 'Pay with card, bank transfer, or mobile money.',
                'admin_notes' => 'Best for African markets. Owned by Stripe.',
                'is_active' => false,
                'config' => [
                    'public_key' => '',
                    'secret_key' => '',
                ],
                'sandbox_config' => [
                    'public_key' => '',
                    'secret_key' => '',
                ],
            ],
            [
                'name' => 'Flutterwave',
                'slug' => 'flutterwave',
                'type' => 'fiat',
                'description' => 'Pan-African payment gateway supporting cards, mobile money, and bank transfers.',
                'logo' => 'flutterwave-logo.png',
                'supported_currencies' => ['NGN', 'GHS', 'KES', 'ZAR', 'USD', 'GBP', 'EUR'],
                'supported_countries' => ['NG', 'GH', 'KE', 'ZA', 'UG', 'TZ'],
                'transaction_fee_percentage' => 1.4,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'NGN',
                'min_amount' => 1.00,
                'max_amount' => 10000000.00,
                'processing_time_minutes' => 1,
                'webhook_url' => '/webhooks/flutterwave',
                'test_mode' => true,
                'sort_order' => 14,
                'user_instructions' => 'Pay with card, bank account, or mobile money.',
                'admin_notes' => 'Supports multiple African countries and currencies.',
                'is_active' => false,
                'config' => [
                    'public_key' => '',
                    'secret_key' => '',
                    'encryption_key' => '',
                ],
                'sandbox_config' => [
                    'public_key' => '',
                    'secret_key' => '',
                    'encryption_key' => '',
                ],
            ],
            [
                'name' => 'Bitcoin (BTC)',
                'slug' => 'bitcoin',
                'type' => 'crypto',
                'description' => 'Accept Bitcoin payments with on-chain confirmations.',
                'logo' => 'bitcoin-logo.png',
                'supported_currencies' => ['BTC'],
                'transaction_fee_percentage' => 1.0,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'BTC',
                'min_amount' => 0.0001,
                'max_amount' => 100.00,
                'processing_time_minutes' => 60, // ~10 minutes per confirmation, 6 confirmations typical
                'test_mode' => false,
                'sort_order' => 20,
                'user_instructions' => 'Send Bitcoin to the provided address. Requires 3 confirmations.',
                'admin_notes' => 'Requires Bitcoin node or payment processor integration.',
                'is_active' => false,
                'config' => [
                    'wallet_address' => '',
                    'required_confirmations' => 3,
                ],
                'sandbox_config' => [
                    'testnet_wallet_address' => '',
                    'required_confirmations' => 1,
                ],
            ],
            [
                'name' => 'Ethereum (ETH)',
                'slug' => 'ethereum',
                'type' => 'crypto',
                'description' => 'Accept Ethereum and ERC-20 tokens.',
                'logo' => 'ethereum-logo.png',
                'supported_currencies' => ['ETH', 'USDT', 'USDC'],
                'transaction_fee_percentage' => 1.0,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'ETH',
                'min_amount' => 0.001,
                'max_amount' => 1000.00,
                'processing_time_minutes' => 15,
                'test_mode' => false,
                'sort_order' => 21,
                'user_instructions' => 'Send Ethereum or ERC-20 tokens to the provided address.',
                'admin_notes' => 'Supports ETH and ERC-20 tokens like USDT and USDC.',
                'is_active' => false,
                'config' => [
                    'wallet_address' => '',
                    'required_confirmations' => 12,
                ],
                'sandbox_config' => [
                    'testnet_wallet_address' => '',
                    'required_confirmations' => 6,
                ],
            ],
            [
                'name' => 'Coinbase Commerce',
                'slug' => 'coinbase',
                'type' => 'crypto',
                'description' => 'Accept Bitcoin, Ethereum, Litecoin, and more through Coinbase Commerce.',
                'logo' => 'coinbase-logo.png',
                'supported_currencies' => ['BTC', 'ETH', 'LTC', 'BCH', 'USDC'],
                'transaction_fee_percentage' => 1.0,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'USD',
                'min_amount' => 1.00,
                'max_amount' => 100000.00,
                'processing_time_minutes' => 15,
                'test_mode' => true,
                'sort_order' => 22,
                'user_instructions' => 'Pay with your preferred cryptocurrency through Coinbase.',
                'admin_notes' => 'Requires Coinbase Commerce account and API key.',
                'is_active' => false,
                'config' => [
                    'api_key' => '',
                    'webhook_secret' => '',
                ],
                'sandbox_config' => [
                    'api_key' => '',
                    'webhook_secret' => '',
                ],
            ],
            [
                'name' => 'USDT (Tether)',
                'slug' => 'usdt',
                'type' => 'crypto',
                'description' => 'Accept USDT stablecoin on multiple blockchain networks.',
                'logo' => 'usdt-logo.png',
                'supported_currencies' => ['USDT'],
                'transaction_fee_percentage' => 0.5,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'USDT',
                'min_amount' => 1.00,
                'max_amount' => 1000000.00,
                'processing_time_minutes' => 5,
                'test_mode' => false,
                'sort_order' => 23,
                'user_instructions' => 'Send USDT (ERC-20, TRC-20, or BEP-20) to the provided address.',
                'admin_notes' => 'Stablecoin pegged to USD. Supports multiple networks.',
                'is_active' => false,
                'config' => [
                    'wallet_address_erc20' => '',
                    'wallet_address_trc20' => '',
                    'wallet_address_bep20' => '',
                    'required_confirmations' => 12,
                ],
                'sandbox_config' => [
                    'testnet_wallet_address_erc20' => '',
                    'testnet_wallet_address_trc20' => '',
                    'testnet_wallet_address_bep20' => '',
                    'required_confirmations' => 6,
                ],
            ],
            [
                'name' => 'Internal Wallet',
                'slug' => 'wallet',
                'type' => 'wallet',
                'description' => 'Pay using your account wallet balance.',
                'logo' => 'wallet-logo.png',
                'supported_currencies' => ['USD', 'EUR', 'GBP', 'INR'],
                'transaction_fee_percentage' => 0.0,
                'transaction_fee_fixed' => 0.00,
                'transaction_fee_currency' => 'USD',
                'min_amount' => 0.01,
                'max_amount' => 999999.99,
                'processing_time_minutes' => 0,
                'test_mode' => false,
                'sort_order' => 0,
                'user_instructions' => 'Instantly pay using your wallet balance.',
                'admin_notes' => 'Internal wallet system. No fees applied.',
                'is_active' => true,
                'config' => [],
            ],
        ];

        foreach ($gateways as $gateway) {
            PaymentGateway::updateOrCreate(
                ['slug' => $gateway['slug']],
                $gateway
            );
        }
    }
}
